// Products
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const ORDER_PRODUCTS_BY_PRICE = 'ORDER_PRODUCTS_BY_PRICE'
export const ORDER_PRODUCTS_BY_NAME = 'ORDER_PRODUCTS_BY_NAME'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const GET_PRODUCT_TOP = 'GET_PRODUCT_TOP'

//SearchBar
export const GET_PRODUCTS_BY_NAME = 'GET_PRODUCTS_BY_NAME'

//Details
export const GET_DETAIL = "GET_DETAIL"

//Categories
export const GET_CATEGORIES = "GET_CATEGORIES"
export const FILTER_BY_CATEGORIES = "FILTER_BY_CATEGORIES"
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const DELETE_CATEGORIES = "DELETE_CATEGORIES"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"

//Favorites
export const ADD_ITEM_FAVORITES = "ADD_ITEM_FAVORITES"
export const DELETE_ITEM_FAVORITES = "DELETE_ITEM_FAVORITES"
export const GET_ALL_FAV = "GET_ALL_FAV"

//Cart
export const ADD_ITEM = "ADD_ITEM"
export const ADD_ITEM_INPUT = "ADD_ITEM_INPUT"
export const DELETE_ITEM = "DELETE_ITEM"
export const REMOVE_ITEM = "REMOVE_ITEM"
export const GET_ALL_CART = "GET_ALL_CART"
export const GET_TOTAL_PRICE = "GET_TOTAL_PRICE"
export const GET_TOTAL_ITEMS = "GET_TOTAL_ITEMS"
export const DELETE_ALL_CART = "DELETE_ALL_CART"

//User
export const GET_USER_DATA = "GET_USER_DATA"
export const GET_ALL_USERS = "GET_ALL_USERS"

//Reviews
export const GET_PRODUCT_REVIEWS = 'GET_PRODUCT_REVIEW'

//OrderUser
export const GET_ORDERS_USER = 'GET_ORDERS_USER'
export const CREATE_ORDER_USER = 'CREATE_ORDER_USER'
export const UPDATE_ORDER_USER = 'UPDATE_ORDER_USER'

//Admin

export const GET_ALL_ORDERS = 'GER_ALL_ORDERS'
export const GET_ORDER_DETAIL = 'GET_ORDER_DETAIL'
export const FILTER_ORDERS_PAYMENT = 'FILTER_ORDERS_PAYMENT'
export const FILTER_ORDERS_PURCHASE = 'FILTER_ORDERS_PURCHASE'
